-- MySQL Script generated by MySQL Workbench
-- Mon Aug 11 10:33:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema cuchuflito_sa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cuchuflito_sa` ;

-- -----------------------------------------------------
-- Schema cuchuflito_sa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cuchuflito_sa` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `cuchuflito_sa` ;

-- -----------------------------------------------------
-- Table `cuchuflito_sa`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cuchuflito_sa`.`clientes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cuchuflito_sa`.`clientes` (
  `ID_Cliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NULL DEFAULT NULL,
  `Telefono` VARCHAR(45) NULL DEFAULT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Documento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `ID_Cliente_UNIQUE` ON `cuchuflito_sa`.`clientes` (`ID_Cliente` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Documento_UNIQUE` ON `cuchuflito_sa`.`clientes` (`Documento` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cuchuflito_sa`.`compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cuchuflito_sa`.`compras` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cuchuflito_sa`.`compras` (
  `ID_Compras` INT NOT NULL AUTO_INCREMENT,
  `ID_Proveedor` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Total` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`ID_Compras`),
  CONSTRAINT `FK_ID_Proveedor`
    FOREIGN KEY (`ID_Proveedor`)
    REFERENCES `cuchuflito_sa`.`proveedores` (`ID_Proveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `ID_Compras_UNIQUE` ON `cuchuflito_sa`.`compras` (`ID_Compras` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `FK_ID_Proveedor_idx` ON `cuchuflito_sa`.`compras` (`ID_Proveedor` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cuchuflito_sa`.`compras_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cuchuflito_sa`.`compras_productos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cuchuflito_sa`.`compras_productos` (
  `ID_Compras` INT NOT NULL,
  `ID_Producto` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Precio_Unitario` DECIMAL(10,0) NOT NULL,
  CONSTRAINT `FK_ID_Compras`
    FOREIGN KEY (`ID_Compras`)
    REFERENCES `cuchuflito_sa`.`compras` (`ID_Compras`),
  CONSTRAINT `FK_ID_Producto`
    FOREIGN KEY (`ID_Producto`)
    REFERENCES `cuchuflito_sa`.`productos` (`ID_Producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `FK_ID_Compras_idx` ON `cuchuflito_sa`.`compras_productos` (`ID_Compras` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `FK_ID_Producto_idx` ON `cuchuflito_sa`.`compras_productos` (`ID_Producto` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cuchuflito_sa`.`medios_de_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cuchuflito_sa`.`medios_de_pago` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cuchuflito_sa`.`medios_de_pago` (
  `ID_Medio` INT NOT NULL,
  `Medio_de_Pago` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Medio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cuchuflito_sa`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cuchuflito_sa`.`productos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cuchuflito_sa`.`productos` (
  `ID_Producto` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Descripcion` TEXT NULL DEFAULT NULL,
  `Precio` DECIMAL(10,0) NULL DEFAULT NULL,
  `ID_Proveedor` INT NOT NULL,
  `Stock` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Producto`))
ENGINE = InnoDB
AUTO_INCREMENT = 72
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `ID_Producto_UNIQUE` ON `cuchuflito_sa`.`productos` (`ID_Producto` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cuchuflito_sa`.`proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cuchuflito_sa`.`proveedores` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cuchuflito_sa`.`proveedores` (
  `ID_Proveedor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Proveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `ID_Proveedor_UNIQUE` ON `cuchuflito_sa`.`proveedores` (`ID_Proveedor` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cuchuflito_sa`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cuchuflito_sa`.`ventas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cuchuflito_sa`.`ventas` (
  `ID_Ventas` INT NOT NULL AUTO_INCREMENT,
  `ID_Cliente` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Total` DECIMAL(10,0) NOT NULL,
  `Medio_de_pago` INT NOT NULL,
  PRIMARY KEY (`ID_Ventas`),
  CONSTRAINT `FK_Medio_Pago`
    FOREIGN KEY (`Medio_de_pago`)
    REFERENCES `cuchuflito_sa`.`medios_de_pago` (`ID_Medio`),
  CONSTRAINT `FK_Ventas_Clientes`
    FOREIGN KEY (`ID_Cliente`)
    REFERENCES `cuchuflito_sa`.`clientes` (`ID_Cliente`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `ID_Ventas_UNIQUE` ON `cuchuflito_sa`.`ventas` (`ID_Ventas` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `FK_Ventas_Clientes_idx` ON `cuchuflito_sa`.`ventas` (`ID_Cliente` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `FK_Medio:Pago_idx` ON `cuchuflito_sa`.`ventas` (`Medio_de_pago` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cuchuflito_sa`.`ventas_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cuchuflito_sa`.`ventas_productos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cuchuflito_sa`.`ventas_productos` (
  `ID_Ventas` INT NOT NULL,
  `ID_Producto` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Precio_Unitario` DECIMAL(10,0) NOT NULL,
  CONSTRAINT `FK_ID_Venta`
    FOREIGN KEY (`ID_Ventas`)
    REFERENCES `cuchuflito_sa`.`ventas` (`ID_Ventas`),
  CONSTRAINT `FK_Venta_Producto`
    FOREIGN KEY (`ID_Producto`)
    REFERENCES `cuchuflito_sa`.`productos` (`ID_Producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `FK_ID_Producto_idx` ON `cuchuflito_sa`.`ventas_productos` (`ID_Producto` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `FK_OD_Venta_idx` ON `cuchuflito_sa`.`ventas_productos` (`ID_Ventas` ASC) VISIBLE;

SHOW WARNINGS;
USE `cuchuflito_sa` ;

-- -----------------------------------------------------
-- Placeholder table for view `cuchuflito_sa`.`vista_compras_detalladas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuchuflito_sa`.`vista_compras_detalladas` (`ID_Compras` INT, `Fecha` INT, `Producto` INT, `Cantidad` INT, `Precio_Unitario` INT, `Proveedor` INT, `Email` INT);
SHOW WARNINGS;

-- -----------------------------------------------------
-- Placeholder table for view `cuchuflito_sa`.`vista_productos_agrupados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuchuflito_sa`.`vista_productos_agrupados` (`Nombre` INT, `stock_total` INT, `descripciones` INT, `costos` INT);
SHOW WARNINGS;

-- -----------------------------------------------------
-- Placeholder table for view `cuchuflito_sa`.`vista_ventas_detalladas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuchuflito_sa`.`vista_ventas_detalladas` (`ID_Ventas` INT, `Fecha` INT, `Producto` INT, `Cantidad` INT, `Precio_Unitario` INT, `Medio_de_Pago` INT, `Cliente` INT, `Apellido_Cliente` INT);
SHOW WARNINGS;

-- -----------------------------------------------------
-- View `cuchuflito_sa`.`vista_compras_detalladas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cuchuflito_sa`.`vista_compras_detalladas`;
SHOW WARNINGS;
DROP VIEW IF EXISTS `cuchuflito_sa`.`vista_compras_detalladas` ;
SHOW WARNINGS;
USE `cuchuflito_sa`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `cuchuflito_sa`.`vista_compras_detalladas` AS select `c`.`ID_Compras` AS `ID_Compras`,`c`.`Fecha` AS `Fecha`,`pr`.`Nombre` AS `Producto`,`cp`.`Cantidad` AS `Cantidad`,`cp`.`Precio_Unitario` AS `Precio_Unitario`,`prov`.`Nombre` AS `Proveedor`,`prov`.`Email` AS `Email` from (((`cuchuflito_sa`.`compras` `c` join `cuchuflito_sa`.`compras_productos` `cp` on((`c`.`ID_Compras` = `cp`.`ID_Compras`))) join `cuchuflito_sa`.`productos` `pr` on((`cp`.`ID_Producto` = `pr`.`ID_Producto`))) join `cuchuflito_sa`.`proveedores` `prov` on((`c`.`ID_Proveedor` = `prov`.`ID_Proveedor`)));
SHOW WARNINGS;

-- -----------------------------------------------------
-- View `cuchuflito_sa`.`vista_productos_agrupados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cuchuflito_sa`.`vista_productos_agrupados`;
SHOW WARNINGS;
DROP VIEW IF EXISTS `cuchuflito_sa`.`vista_productos_agrupados` ;
SHOW WARNINGS;
USE `cuchuflito_sa`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `cuchuflito_sa`.`vista_productos_agrupados` AS select `cuchuflito_sa`.`productos`.`Nombre` AS `Nombre`,sum(`cuchuflito_sa`.`productos`.`Stock`) AS `stock_total`,group_concat(distinct `cuchuflito_sa`.`productos`.`Descripcion` separator '; ') AS `descripciones`,group_concat(distinct `cuchuflito_sa`.`productos`.`Precio` separator '; ') AS `costos` from `cuchuflito_sa`.`productos` group by `cuchuflito_sa`.`productos`.`Nombre`;
SHOW WARNINGS;

-- -----------------------------------------------------
-- View `cuchuflito_sa`.`vista_ventas_detalladas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cuchuflito_sa`.`vista_ventas_detalladas`;
SHOW WARNINGS;
DROP VIEW IF EXISTS `cuchuflito_sa`.`vista_ventas_detalladas` ;
SHOW WARNINGS;
USE `cuchuflito_sa`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `cuchuflito_sa`.`vista_ventas_detalladas` AS select `v`.`ID_Ventas` AS `ID_Ventas`,`v`.`Fecha` AS `Fecha`,`p`.`Nombre` AS `Producto`,`vp`.`Cantidad` AS `Cantidad`,`vp`.`Precio_Unitario` AS `Precio_Unitario`,`mp`.`Medio_de_Pago` AS `Medio_de_Pago`,`c`.`Nombre` AS `Cliente`,`c`.`Apellido` AS `Apellido_Cliente` from ((((`cuchuflito_sa`.`ventas` `v` join `cuchuflito_sa`.`ventas_productos` `vp` on((`v`.`ID_Ventas` = `vp`.`ID_Ventas`))) join `cuchuflito_sa`.`productos` `p` on((`vp`.`ID_Producto` = `p`.`ID_Producto`))) join `cuchuflito_sa`.`medios_de_pago` `mp` on((`v`.`Medio_de_pago` = `mp`.`ID_Medio`))) join `cuchuflito_sa`.`clientes` `c` on((`v`.`ID_Cliente` = `c`.`ID_Cliente`)));
SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
