-- MySQL Script generated by MySQL Workbench
-- Sun Aug 10 09:45:39 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cuchuflito_sa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cuchuflito_sa` ;

-- -----------------------------------------------------
-- Schema cuchuflito_sa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cuchuflito_sa` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cuchuflito_sa` ;

-- -----------------------------------------------------
-- Table `cuchuflito_sa`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cuchuflito_sa`.`clientes` ;

CREATE TABLE IF NOT EXISTS `cuchuflito_sa`.`clientes` (
  `ID_Cliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NULL DEFAULT NULL,
  `Telefono` VARCHAR(45) NULL DEFAULT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Documento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Cliente`),
  UNIQUE INDEX `ID_Cliente_UNIQUE` (`ID_Cliente` ASC) VISIBLE,
  UNIQUE INDEX `Documento_UNIQUE` (`Documento` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cuchuflito_sa`.`proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cuchuflito_sa`.`proveedores` ;

CREATE TABLE IF NOT EXISTS `cuchuflito_sa`.`proveedores` (
  `ID_Proveedor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Proveedor`),
  UNIQUE INDEX `ID_Proveedor_UNIQUE` (`ID_Proveedor` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cuchuflito_sa`.`compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cuchuflito_sa`.`compras` ;

CREATE TABLE IF NOT EXISTS `cuchuflito_sa`.`compras` (
  `ID_Compras` INT NOT NULL AUTO_INCREMENT,
  `ID_Proveedor` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Total` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`ID_Compras`),
  UNIQUE INDEX `ID_Compras_UNIQUE` (`ID_Compras` ASC) VISIBLE,
  INDEX `FK_ID_Proveedor_idx` (`ID_Proveedor` ASC) VISIBLE,
  CONSTRAINT `FK_ID_Proveedor`
    FOREIGN KEY (`ID_Proveedor`)
    REFERENCES `cuchuflito_sa`.`proveedores` (`ID_Proveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cuchuflito_sa`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cuchuflito_sa`.`productos` ;

CREATE TABLE IF NOT EXISTS `cuchuflito_sa`.`productos` (
  `ID_Producto` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Descripcion` TEXT NULL DEFAULT NULL,
  `Precio` DECIMAL(10,0) NULL DEFAULT NULL,
  `ID_Proveedor` INT NOT NULL,
  `Stock` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Producto`),
  UNIQUE INDEX `ID_Producto_UNIQUE` (`ID_Producto` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 72
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cuchuflito_sa`.`compras_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cuchuflito_sa`.`compras_productos` ;

CREATE TABLE IF NOT EXISTS `cuchuflito_sa`.`compras_productos` (
  `ID_Compras` INT NOT NULL,
  `ID_Producto` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Precio_Unitario` DECIMAL(10,0) NOT NULL,
  INDEX `FK_ID_Compras_idx` (`ID_Compras` ASC) VISIBLE,
  INDEX `FK_ID_Producto_idx` (`ID_Producto` ASC) VISIBLE,
  CONSTRAINT `FK_ID_Compras`
    FOREIGN KEY (`ID_Compras`)
    REFERENCES `cuchuflito_sa`.`compras` (`ID_Compras`),
  CONSTRAINT `FK_ID_Producto`
    FOREIGN KEY (`ID_Producto`)
    REFERENCES `cuchuflito_sa`.`productos` (`ID_Producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cuchuflito_sa`.`medios_de_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cuchuflito_sa`.`medios_de_pago` ;

CREATE TABLE IF NOT EXISTS `cuchuflito_sa`.`medios_de_pago` (
  `ID_Medio` INT NOT NULL,
  `Medio_de_Pago` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Medio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cuchuflito_sa`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cuchuflito_sa`.`ventas` ;

CREATE TABLE IF NOT EXISTS `cuchuflito_sa`.`ventas` (
  `ID_Ventas` INT NOT NULL AUTO_INCREMENT,
  `ID_Cliente` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Total` DECIMAL(10,0) NOT NULL,
  `Medio_de_pago` INT NOT NULL,
  PRIMARY KEY (`ID_Ventas`),
  UNIQUE INDEX `ID_Ventas_UNIQUE` (`ID_Ventas` ASC) VISIBLE,
  INDEX `FK_Ventas_Clientes_idx` (`ID_Cliente` ASC) VISIBLE,
  INDEX `FK_Medio:Pago_idx` (`Medio_de_pago` ASC) VISIBLE,
  CONSTRAINT `FK_Medio_Pago`
    FOREIGN KEY (`Medio_de_pago`)
    REFERENCES `cuchuflito_sa`.`medios_de_pago` (`ID_Medio`),
  CONSTRAINT `FK_Ventas_Clientes`
    FOREIGN KEY (`ID_Cliente`)
    REFERENCES `cuchuflito_sa`.`clientes` (`ID_Cliente`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cuchuflito_sa`.`ventas_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cuchuflito_sa`.`ventas_productos` ;

CREATE TABLE IF NOT EXISTS `cuchuflito_sa`.`ventas_productos` (
  `ID_Ventas` INT NOT NULL,
  `ID_Producto` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Precio_Unitario` DECIMAL(10,0) NOT NULL,
  INDEX `FK_ID_Producto_idx` (`ID_Producto` ASC) VISIBLE,
  INDEX `FK_OD_Venta_idx` (`ID_Ventas` ASC) VISIBLE,
  CONSTRAINT `FK_ID_Venta`
    FOREIGN KEY (`ID_Ventas`)
    REFERENCES `cuchuflito_sa`.`ventas` (`ID_Ventas`),
  CONSTRAINT `FK_Venta_Producto`
    FOREIGN KEY (`ID_Producto`)
    REFERENCES `cuchuflito_sa`.`productos` (`ID_Producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
